name: CI/CD Pipeline for Docker Assignment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t simrankaramchandani/docker_assignment:latest .

      - name: Push Docker image to Docker Hub
        run: |
          docker push simrankaramchandani/docker_assignment:latest
